### ISSUE TITLE
大佬，我在Ubuntu上跑训练的时候报这个错误一直找不到解决方法能帮我看看吗

### ISSUE THREAD

**Issue by txg-GANGGANG** [bubbliiiing/classification-pytorch#17]
Traceback (most recent call last):  File "train.py", line 452, in <module>
    fit_one_epoch(model_train, model, loss_history, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, save_period, save_dir, local_rank)
  File "/mnt/class_master/utils/utils_fit.py", line 116, in fit_one_epoch    if (math.floor(epoch) + 1) % save_period == 0 or math.floor(epoch)+1 == Epoch:
TypeError: unsupported operand type(s) for %: 'int' and 'str'

**Comment by bubbliiiing** [comment]
你的Epoch为啥是一个str呀

**Comment by bubbliiiing** [comment]
0 0
